### ISSUE TITLE
Remove any mentions to Infinite Red

### ISSUE THREAD

**Issue by sidferreira** [sidferreira/ignite-web-boilerplate#1]
The infinite Red team isn't a direct/active supporter of this project (yet).
So we need to remove any mention to them.

Also, add a comment being clear that this project is deeply inspired in Infinite Red's Ignite boilerplate.

**Comment by cogwizzle** [comment]
I can work on this.

**Comment by cogwizzle** [comment]
I have to code changes on a branch but I am not able to commit them.  Is there another preferred way for me to contribute?

**Comment by sidferreira** [comment]
You need to make a pull request

**Comment by cogwizzle** [comment]
@sidferreira Sorry I am a bit new to this.  I believe I need to push a branch to the repository before I can create a pull request.  Each time I try to commit my changes I get an error about permissions being denied.  I have tried both SSL and SSH versions of the URL.  Am I missing something?

**Comment by cogwizzle** [comment]
I was able to get help in the slack channel.  Sorry for the trouble.  I am a bit new to this process.  Thanks for your patience.

**Comment by sidferreira** [comment]
Thanks a lot @jfehrman !
