### ISSUE TITLE
TODOs, Suggestions and Ideas

### ISSUE THREAD

**Issue by sidferreira** [sidferreira/ignite-web-boilerplate#4]
Feel free to place suggestions about what must be done/added.

**Comment by Hamatek** [comment]
wouldn't it be nice to add graphql support with [apollo ](https://github.com/apollographql/react-apollo) and some styling like [styled-componen](https://www.styled-components.com/)t or [emotion ](https://medium.com/@tkh44/emotion-7-7ef119c45869) or even something like [material-ui](https://material-ui-1dab0.firebaseapp.com/getting-started/installation/) ?

**Comment by sidferreira** [comment]
Hey @hamatek! It's a good idea, but, at the same time, not all projects use graphql or that styles. I think we can add docs about how to use them. But I'm not sure if should be there by default

**Comment by Hamatek** [comment]
As always nothing should be default, maybe using ignite plugins, or just
let user choose when he generate the project ?

Le dim. 17 sept. 2017 à 12:09 AM, Sid Ferreira <notifications@github.com> a
écrit :
